---

- hosts: localhost
  become: yes
  tasks:

    - name: Ensure deploy directories exist
      file:
        path: /opt
        state: directory
    
    
    - name: Download JRE
      command: >
        wget --no-cookies --no-check-certificate \
          --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" \
          "http://download.oracle.com/otn-pub/java/jdk/8u40-b25/jre-8u40-linux-x64.tar.gz"
      args:
        chdir: /opt
    
    
    - name: Unarchive JRE
      command: >
        tar xvf jre-8*.tar.gz
      args:
        chdir: /opt
    
    
    - name: Install JRE
      command: >
        alternatives --install /usr/bin/java java /opt/jre1.8*/bin/java 1
